[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/TouristeProject-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
